@ASP_Project_HostAddress = https://localhost:7292

POST {{ASP_Project_HostAddress}}/todoitems
Content-Type: application/json

{
  "name":"walk dog",
  "isComplete":true
}

###

POST {{ASP_Project_HostAddress}}/todoitems
Content-Type: application/json

{
  "name":"stay dog",
  "isComplete":true
}

###

GET {{ASP_Project_HostAddress}}/todoitems

###

GET {{ASP_Project_HostAddress}}/todoitems/1

###

GET {{ASP_Project_HostAddress}}/todoitems/complete

###

PUT {{ASP_Project_HostAddress}}/todoitems/1
Content-Type: application/json

{
  "name": "feed fish",
  "isComplete": false
}
###

DELETE {{ASP_Project_HostAddress}}/todoitems/1

###
